package com.example.springtgbot.botapi;

public enum BotState {
    START,
    STATISTICS,
    DAILY_WALLET,
    ACCUMULATIVE_WALLET,
    ADD_EXPENSE,
    ADD_INCOME,
    BALANCE_CHANGED,
    SET_BALANCE,
    TRY_SET_BALANCE,
    EXPENSE_CATEGORY,
    INCOME_CATEGORY,
    OTHER_CATEGORY,
    STATISTICS_TODAY,
    STATISTICS_WEEK,
    STATISTICS_MONTH,
    STATISTICS_CHOOSE
}
